### ISSUE TITLE
ccd_playerone: Cannot stop CCD_STREAMING

### ISSUE THREAD

**Issue by tail-feather** [indigo-astronomy/indigo#541] opened 2024-06-04 11:23 UTC
The problem occurs when the streaming frame count is set to `-1`.
This does not occur when a positive integer is set for the streaming frame count.

`CCD_ABORT_EXPOSURE_PROPERTY->state` is not referenced in the streaming loop.
https://github.com/indigo-astronomy/indigo/blob/1aed5efb959caa23efbc3bda0051520c34a6038a/indigo_drivers/ccd_playerone/indigo_ccd_playerone.c#L566

**Comment by rumengb** [comment] 2024-06-04 12:04
The problem is related to exposure time actually if exposure < 1s the streaming can not be stopped. fixed with d80f56115abe63653e1c8fac6ead6b1bb506792c

**Closed by rumengb** 2024-06-04 12:04 UTC

**Comment by tail-feather** [comment] 2024-06-04 14:56
I have confirmed that this has been fixed.
Thank you.
